# Sponsorship and funding information
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [jrc1883]
# custom: ["https://popkit.dev/sponsor"]
