/**
 * README Template
 */

export const readmeTemplate = `# {{PROJECT_NAME}} Dev MCP Server

A project-specific MCP (Model Context Protocol) server generated by [PopKit](https://github.com/jrc1883/popkit-plugin).

## Features

{{#TOOLS_LIST}}

## Installation

\`\`\`bash
cd .mcp-server
npm install
npm run build
\`\`\`

## Configuration

Add to your Claude Code settings (\`.claude/settings.json\`):

\`\`\`json
{
  "mcpServers": {
    "{{PROJECT_NAME}}-dev": {
      "command": "node",
      "args": ["{{MCP_PATH}}/dist/index.js"],
      "env": {
        "WORKSPACE_PATH": "{{WORKSPACE_PATH}}"
      }
    }
  }
}
\`\`\`

## Available Tools

| Tool | Description |
|------|-------------|
{{#TOOLS_TABLE}}

## Usage

Once configured, these tools are available in Claude Code:

- Use \`tool_search\` to find relevant tools by description
- Call tools directly by name with appropriate arguments

## Generated By

This MCP server was generated by PopKit Premium.
Learn more at https://github.com/jrc1883/popkit-plugin
`;
