#!/usr/bin/env python3
"""
Unit tests for tech_stack_detector module.

Tests technology detection across multiple languages and tools.
"""

import json
import tempfile
from pathlib import Path

import pytest

from popkit_shared.utils.tech_stack_detector import (
    TechnologyType,
    TechStackDetector,
    format_tech_stack_report,
)


@pytest.fixture
def temp_project():
    """Create temporary project directory for testing."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


class TestPythonDetection:
    """Test Python technology detection."""

    def test_detect_python_with_pyproject(self, temp_project):
        """Test Python detection via pyproject.toml."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text(
            """
[tool.poetry]
name = "test-project"

[tool.poetry.dependencies]
python = "^3.8"
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        python_tech = next((t for t in stack.technologies if t.name == "Python"), None)
        assert python_tech is not None
        assert python_tech.type == TechnologyType.LANGUAGE
        assert python_tech.confidence == 1.0
        assert "pyproject.toml found" in python_tech.evidence

    def test_detect_python_with_requirements(self, temp_project):
        """Test Python detection via requirements.txt."""
        requirements = temp_project / "requirements.txt"
        requirements.write_text("django>=4.0\nrequests>=2.28\n")

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        python_tech = next((t for t in stack.technologies if t.name == "Python"), None)
        assert python_tech is not None
        assert "requirements.txt found" in python_tech.evidence

    def test_detect_ruff_from_pyproject(self, temp_project):
        """Test Ruff detection from pyproject.toml."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text(
            """
[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_python()

        ruff_tech = next((t for t in detector.technologies if t.name == "Ruff"), None)
        assert ruff_tech is not None
        assert ruff_tech.type == TechnologyType.LINTER
        assert ruff_tech.confidence == 1.0
        assert ruff_tech.config_file == "pyproject.toml"

    def test_detect_black_from_pyproject(self, temp_project):
        """Test Black detection from pyproject.toml."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text(
            """
[tool.black]
line-length = 88
target-version = ['py38']
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_python()

        black_tech = next((t for t in detector.technologies if t.name == "Black"), None)
        assert black_tech is not None
        assert black_tech.type == TechnologyType.FORMATTER
        assert black_tech.confidence == 1.0

    def test_detect_mypy_from_pyproject(self, temp_project):
        """Test mypy detection from pyproject.toml."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text(
            """
[tool.mypy]
python_version = "3.8"
warn_return_any = true
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_python()

        mypy_tech = next((t for t in detector.technologies if t.name == "mypy"), None)
        assert mypy_tech is not None
        assert mypy_tech.type == TechnologyType.LINTER

    def test_detect_poetry(self, temp_project):
        """Test Poetry detection via poetry.lock."""
        poetry_lock = temp_project / "poetry.lock"
        poetry_lock.write_text("# This file is automatically generated by Poetry\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_python()

        poetry_tech = next((t for t in detector.technologies if t.name == "Poetry"), None)
        assert poetry_tech is not None
        assert poetry_tech.type == TechnologyType.PACKAGE_MANAGER
        assert poetry_tech.confidence == 1.0

    def test_detect_pipenv(self, temp_project):
        """Test Pipenv detection via Pipfile."""
        pipfile = temp_project / "Pipfile"
        pipfile.write_text(
            """
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "*"
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_python()

        pipenv_tech = next((t for t in detector.technologies if t.name == "Pipenv"), None)
        assert pipenv_tech is not None
        assert pipenv_tech.type == TechnologyType.PACKAGE_MANAGER

    def test_detect_pytest(self, temp_project):
        """Test pytest detection from pyproject.toml."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text(
            """
[tool.pytest.ini_options]
testpaths = ["tests"]
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_python()

        pytest_tech = next((t for t in detector.technologies if t.name == "pytest"), None)
        assert pytest_tech is not None
        assert pytest_tech.type == TechnologyType.TESTING_FRAMEWORK


class TestJavaScriptDetection:
    """Test JavaScript/TypeScript technology detection."""

    def test_detect_nodejs_from_package_json(self, temp_project):
        """Test Node.js detection via package.json."""
        package_json = temp_project / "package.json"
        package_json.write_text(
            json.dumps(
                {
                    "name": "test-project",
                    "version": "1.0.0",
                    "dependencies": {"express": "^4.18.0"},
                }
            )
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        nodejs_tech = next((t for t in stack.technologies if t.name == "Node.js"), None)
        assert nodejs_tech is not None
        assert nodejs_tech.type == TechnologyType.LANGUAGE
        assert nodejs_tech.confidence == 1.0

    def test_detect_typescript(self, temp_project):
        """Test TypeScript detection via tsconfig.json."""
        package_json = temp_project / "package.json"
        package_json.write_text(json.dumps({"name": "test-project"}))

        tsconfig = temp_project / "tsconfig.json"
        tsconfig.write_text(
            json.dumps(
                {
                    "compilerOptions": {
                        "target": "ES2020",
                        "module": "commonjs",
                    }
                }
            )
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        ts_tech = next((t for t in stack.technologies if t.name == "TypeScript"), None)
        assert ts_tech is not None
        assert ts_tech.type == TechnologyType.LANGUAGE
        assert ts_tech.config_file == "tsconfig.json"

    def test_detect_eslint(self, temp_project):
        """Test ESLint detection via .eslintrc.json."""
        package_json = temp_project / "package.json"
        package_json.write_text(json.dumps({"name": "test-project"}))

        eslintrc = temp_project / ".eslintrc.json"
        eslintrc.write_text(json.dumps({"extends": ["eslint:recommended"]}))

        detector = TechStackDetector(str(temp_project))
        detector.detect_javascript()

        eslint_tech = next((t for t in detector.technologies if t.name == "ESLint"), None)
        assert eslint_tech is not None
        assert eslint_tech.type == TechnologyType.LINTER
        assert eslint_tech.config_file == ".eslintrc.json"

    def test_detect_prettier(self, temp_project):
        """Test Prettier detection via .prettierrc."""
        package_json = temp_project / "package.json"
        package_json.write_text(json.dumps({"name": "test-project"}))

        prettierrc = temp_project / ".prettierrc"
        prettierrc.write_text(json.dumps({"semi": False, "singleQuote": True}))

        detector = TechStackDetector(str(temp_project))
        detector.detect_javascript()

        prettier_tech = next((t for t in detector.technologies if t.name == "Prettier"), None)
        assert prettier_tech is not None
        assert prettier_tech.type == TechnologyType.FORMATTER

    def test_detect_jest(self, temp_project):
        """Test Jest detection from package.json."""
        package_json = temp_project / "package.json"
        package_json.write_text(
            json.dumps(
                {
                    "name": "test-project",
                    "devDependencies": {"jest": "^29.0.0"},
                }
            )
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_javascript()

        jest_tech = next((t for t in detector.technologies if t.name == "Jest"), None)
        assert jest_tech is not None
        assert jest_tech.type == TechnologyType.TESTING_FRAMEWORK
        assert jest_tech.version == "^29.0.0"

    def test_detect_yarn(self, temp_project):
        """Test Yarn detection via yarn.lock."""
        package_json = temp_project / "package.json"
        package_json.write_text(json.dumps({"name": "test-project"}))

        yarn_lock = temp_project / "yarn.lock"
        yarn_lock.write_text("# THIS IS AN AUTOGENERATED FILE.\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_javascript()

        yarn_tech = next((t for t in detector.technologies if t.name == "Yarn"), None)
        assert yarn_tech is not None
        assert yarn_tech.type == TechnologyType.PACKAGE_MANAGER
        assert yarn_tech.confidence == 1.0

    def test_detect_pnpm(self, temp_project):
        """Test pnpm detection via pnpm-lock.yaml."""
        package_json = temp_project / "package.json"
        package_json.write_text(json.dumps({"name": "test-project"}))

        pnpm_lock = temp_project / "pnpm-lock.yaml"
        pnpm_lock.write_text("lockfileVersion: '6.0'\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_javascript()

        pnpm_tech = next((t for t in detector.technologies if t.name == "pnpm"), None)
        assert pnpm_tech is not None
        assert pnpm_tech.type == TechnologyType.PACKAGE_MANAGER


class TestRustDetection:
    """Test Rust technology detection."""

    def test_detect_rust(self, temp_project):
        """Test Rust detection via Cargo.toml."""
        cargo_toml = temp_project / "Cargo.toml"
        cargo_toml.write_text(
            """
[package]
name = "test-project"
version = "0.1.0"
edition = "2021"
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        rust_tech = next((t for t in stack.technologies if t.name == "Rust"), None)
        assert rust_tech is not None
        assert rust_tech.type == TechnologyType.LANGUAGE
        assert rust_tech.confidence == 1.0

    def test_detect_cargo(self, temp_project):
        """Test Cargo detection."""
        cargo_toml = temp_project / "Cargo.toml"
        cargo_toml.write_text("[package]\nname = 'test'\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_rust()

        cargo_tech = next((t for t in detector.technologies if t.name == "Cargo"), None)
        assert cargo_tech is not None
        assert cargo_tech.type == TechnologyType.PACKAGE_MANAGER

    def test_detect_clippy(self, temp_project):
        """Test Clippy detection (inferred from Rust)."""
        cargo_toml = temp_project / "Cargo.toml"
        cargo_toml.write_text("[package]\nname = 'test'\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_rust()

        clippy_tech = next((t for t in detector.technologies if t.name == "Clippy"), None)
        assert clippy_tech is not None
        assert clippy_tech.type == TechnologyType.LINTER

    def test_detect_rustfmt(self, temp_project):
        """Test rustfmt detection (inferred from Rust)."""
        cargo_toml = temp_project / "Cargo.toml"
        cargo_toml.write_text("[package]\nname = 'test'\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_rust()

        rustfmt_tech = next((t for t in detector.technologies if t.name == "rustfmt"), None)
        assert rustfmt_tech is not None
        assert rustfmt_tech.type == TechnologyType.FORMATTER


class TestGoDetection:
    """Test Go technology detection."""

    def test_detect_go(self, temp_project):
        """Test Go detection via go.mod."""
        go_mod = temp_project / "go.mod"
        go_mod.write_text(
            """
module example.com/test

go 1.21
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        go_tech = next((t for t in stack.technologies if t.name == "Go"), None)
        assert go_tech is not None
        assert go_tech.type == TechnologyType.LANGUAGE
        assert go_tech.confidence == 1.0

    def test_detect_go_modules(self, temp_project):
        """Test Go Modules detection."""
        go_mod = temp_project / "go.mod"
        go_mod.write_text("module example.com/test\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_go()

        modules_tech = next((t for t in detector.technologies if t.name == "Go Modules"), None)
        assert modules_tech is not None
        assert modules_tech.type == TechnologyType.PACKAGE_MANAGER

    def test_detect_golangci_lint(self, temp_project):
        """Test golangci-lint detection via config file."""
        go_mod = temp_project / "go.mod"
        go_mod.write_text("module example.com/test\n")

        golangci = temp_project / ".golangci.yml"
        golangci.write_text(
            """
linters:
  enable:
    - gofmt
    - govet
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_go()

        lint_tech = next((t for t in detector.technologies if t.name == "golangci-lint"), None)
        assert lint_tech is not None
        assert lint_tech.type == TechnologyType.LINTER
        assert lint_tech.config_file == ".golangci.yml"

    def test_detect_gofmt(self, temp_project):
        """Test gofmt detection (inferred from Go)."""
        go_mod = temp_project / "go.mod"
        go_mod.write_text("module example.com/test\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_go()

        gofmt_tech = next((t for t in detector.technologies if t.name == "gofmt"), None)
        assert gofmt_tech is not None
        assert gofmt_tech.type == TechnologyType.FORMATTER


class TestRubyDetection:
    """Test Ruby technology detection."""

    def test_detect_ruby(self, temp_project):
        """Test Ruby detection via Gemfile."""
        gemfile = temp_project / "Gemfile"
        gemfile.write_text(
            """
source 'https://rubygems.org'

gem 'rails', '~> 7.0'
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        ruby_tech = next((t for t in stack.technologies if t.name == "Ruby"), None)
        assert ruby_tech is not None
        assert ruby_tech.type == TechnologyType.LANGUAGE

    def test_detect_bundler(self, temp_project):
        """Test Bundler detection."""
        gemfile = temp_project / "Gemfile"
        gemfile.write_text("source 'https://rubygems.org'\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_ruby()

        bundler_tech = next((t for t in detector.technologies if t.name == "Bundler"), None)
        assert bundler_tech is not None
        assert bundler_tech.type == TechnologyType.PACKAGE_MANAGER

    def test_detect_rubocop(self, temp_project):
        """Test RuboCop detection via config file."""
        gemfile = temp_project / "Gemfile"
        gemfile.write_text("source 'https://rubygems.org'\n")

        rubocop = temp_project / ".rubocop.yml"
        rubocop.write_text(
            """
AllCops:
  TargetRubyVersion: 3.0
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_ruby()

        rubocop_tech = next((t for t in detector.technologies if t.name == "RuboCop"), None)
        assert rubocop_tech is not None
        assert rubocop_tech.type == TechnologyType.LINTER


class TestJavaDetection:
    """Test Java technology detection."""

    def test_detect_java_with_maven(self, temp_project):
        """Test Java detection via pom.xml."""
        pom_xml = temp_project / "pom.xml"
        pom_xml.write_text(
            """
<?xml version="1.0" encoding="UTF-8"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>test-project</artifactId>
    <version>1.0-SNAPSHOT</version>
</project>
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        java_tech = next((t for t in stack.technologies if t.name == "Java"), None)
        assert java_tech is not None
        assert java_tech.type == TechnologyType.LANGUAGE

    def test_detect_maven(self, temp_project):
        """Test Maven detection."""
        pom_xml = temp_project / "pom.xml"
        pom_xml.write_text("<project></project>")

        detector = TechStackDetector(str(temp_project))
        detector.detect_java()

        maven_tech = next((t for t in detector.technologies if t.name == "Maven"), None)
        assert maven_tech is not None
        assert maven_tech.type == TechnologyType.BUILD_TOOL
        assert maven_tech.config_file == "pom.xml"

    def test_detect_gradle(self, temp_project):
        """Test Gradle detection."""
        build_gradle = temp_project / "build.gradle"
        build_gradle.write_text(
            """
plugins {
    id 'java'
}
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_java()

        gradle_tech = next((t for t in detector.technologies if t.name == "Gradle"), None)
        assert gradle_tech is not None
        assert gradle_tech.type == TechnologyType.BUILD_TOOL


class TestCppDetection:
    """Test C/C++ technology detection."""

    def test_detect_cpp_with_cmake(self, temp_project):
        """Test C/C++ detection via CMakeLists.txt."""
        cmake = temp_project / "CMakeLists.txt"
        cmake.write_text(
            """
cmake_minimum_required(VERSION 3.10)
project(TestProject)
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        cpp_tech = next((t for t in stack.technologies if t.name == "C/C++"), None)
        assert cpp_tech is not None
        assert cpp_tech.type == TechnologyType.LANGUAGE

    def test_detect_cmake(self, temp_project):
        """Test CMake detection."""
        cmake = temp_project / "CMakeLists.txt"
        cmake.write_text("cmake_minimum_required(VERSION 3.10)\n")

        detector = TechStackDetector(str(temp_project))
        detector.detect_cpp()

        cmake_tech = next((t for t in detector.technologies if t.name == "CMake"), None)
        assert cmake_tech is not None
        assert cmake_tech.type == TechnologyType.BUILD_TOOL

    def test_detect_clang_tidy(self, temp_project):
        """Test clang-tidy detection."""
        cmake = temp_project / "CMakeLists.txt"
        cmake.write_text("cmake_minimum_required(VERSION 3.10)\n")

        clang_tidy = temp_project / ".clang-tidy"
        clang_tidy.write_text(
            """
Checks: 'readability-*,modernize-*'
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_cpp()

        tidy_tech = next((t for t in detector.technologies if t.name == "clang-tidy"), None)
        assert tidy_tech is not None
        assert tidy_tech.type == TechnologyType.LINTER


class TestDatabaseDetection:
    """Test database technology detection."""

    def test_detect_postgresql(self, temp_project):
        """Test PostgreSQL detection from docker-compose."""
        docker_compose = temp_project / "docker-compose.yml"
        docker_compose.write_text(
            """
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: secret
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_databases()

        postgres_tech = next((t for t in detector.technologies if t.name == "PostgreSQL"), None)
        assert postgres_tech is not None
        assert postgres_tech.type == TechnologyType.DATABASE

    def test_detect_mysql(self, temp_project):
        """Test MySQL detection from docker-compose."""
        docker_compose = temp_project / "docker-compose.yml"
        docker_compose.write_text(
            """
services:
  db:
    image: mysql:8.0
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_databases()

        mysql_tech = next((t for t in detector.technologies if t.name == "MySQL"), None)
        assert mysql_tech is not None
        assert mysql_tech.type == TechnologyType.DATABASE

    def test_detect_mongodb(self, temp_project):
        """Test MongoDB detection from docker-compose."""
        docker_compose = temp_project / "docker-compose.yml"
        docker_compose.write_text(
            """
services:
  db:
    image: mongo:6.0
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_databases()

        mongo_tech = next((t for t in detector.technologies if t.name == "MongoDB"), None)
        assert mongo_tech is not None
        assert mongo_tech.type == TechnologyType.DATABASE

    def test_detect_redis(self, temp_project):
        """Test Redis detection from docker-compose."""
        docker_compose = temp_project / "docker-compose.yml"
        docker_compose.write_text(
            """
services:
  cache:
    image: redis:7.0
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_databases()

        redis_tech = next((t for t in detector.technologies if t.name == "Redis"), None)
        assert redis_tech is not None
        assert redis_tech.type == TechnologyType.DATABASE


class TestContainerDetection:
    """Test containerization technology detection."""

    def test_detect_docker(self, temp_project):
        """Test Docker detection via Dockerfile."""
        dockerfile = temp_project / "Dockerfile"
        dockerfile.write_text(
            """
FROM python:3.11
WORKDIR /app
COPY . .
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_containers()

        docker_tech = next((t for t in detector.technologies if t.name == "Docker"), None)
        assert docker_tech is not None
        assert docker_tech.type == TechnologyType.CONTAINERIZATION
        assert docker_tech.config_file == "Dockerfile"

    def test_detect_docker_compose(self, temp_project):
        """Test Docker Compose detection."""
        docker_compose = temp_project / "docker-compose.yml"
        docker_compose.write_text(
            """
version: '3.8'
services:
  web:
    image: nginx
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_containers()

        compose_tech = next((t for t in detector.technologies if t.name == "Docker Compose"), None)
        assert compose_tech is not None
        assert compose_tech.type == TechnologyType.CONTAINERIZATION

    def test_detect_kubernetes(self, temp_project):
        """Test Kubernetes detection via k8s directory."""
        k8s_dir = temp_project / "k8s"
        k8s_dir.mkdir()
        deployment = k8s_dir / "deployment.yaml"
        deployment.write_text(
            """
apiVersion: apps/v1
kind: Deployment
"""
        )

        detector = TechStackDetector(str(temp_project))
        detector.detect_containers()

        k8s_tech = next((t for t in detector.technologies if t.name == "Kubernetes"), None)
        assert k8s_tech is not None
        assert k8s_tech.type == TechnologyType.CONTAINERIZATION


class TestMultiLanguageProjects:
    """Test detection in multi-language projects."""

    def test_detect_python_and_javascript(self, temp_project):
        """Test detection of both Python and JavaScript in same project."""
        # Python files
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text("[tool.poetry]\nname = 'test'\n")

        # JavaScript files
        package_json = temp_project / "package.json"
        package_json.write_text(json.dumps({"name": "test"}))

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        languages = [t for t in stack.technologies if t.type == TechnologyType.LANGUAGE]
        language_names = [t.name for t in languages]

        assert "Python" in language_names
        assert "Node.js" in language_names

    def test_primary_language_highest_confidence(self, temp_project):
        """Test that primary language is determined by highest confidence."""
        # Create Python project (high confidence)
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text("[tool.poetry]\nname = 'test'\n")

        # Create minimal C/C++ indicators (lower confidence)
        makefile = temp_project / "Makefile"
        makefile.write_text("all:\n\techo 'build'\n")

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        # Python has confidence 1.0, C/C++ has 0.9
        assert stack.primary_language == "Python"


class TestTechStackAnalysis:
    """Test overall tech stack analysis."""

    def test_confidence_score_calculation(self, temp_project):
        """Test overall confidence score calculation."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text(
            """
[tool.poetry]
name = "test"

[tool.ruff]
line-length = 100
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        # Confidence is average of all detections
        assert 0.0 < stack.confidence_score <= 1.0

    def test_config_files_tracking(self, temp_project):
        """Test that config files are tracked."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text("[tool.poetry]\nname = 'test'\n")

        package_json = temp_project / "package.json"
        package_json.write_text(json.dumps({"name": "test"}))

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        assert "pyproject.toml" in stack.config_files_found
        assert "package.json" in stack.config_files_found

    def test_warnings_for_invalid_json(self, temp_project):
        """Test warnings for invalid JSON files."""
        package_json = temp_project / "package.json"
        package_json.write_text("{ invalid json }")

        detector = TechStackDetector(str(temp_project))
        detector.detect_javascript()

        assert len(detector.warnings) > 0
        assert "Invalid JSON" in detector.warnings[0]

    def test_empty_project(self, temp_project):
        """Test detection on empty project."""
        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()

        assert len(stack.technologies) == 0
        assert stack.primary_language is None
        assert stack.confidence_score == 0.0


class TestReportFormatting:
    """Test tech stack report formatting."""

    def test_format_basic_report(self, temp_project):
        """Test basic report formatting."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text(
            """
[tool.poetry]
name = "test"

[tool.ruff]
line-length = 100
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()
        report = format_tech_stack_report(stack)

        assert "# Tech Stack Analysis" in report
        assert "Primary Language" in report
        assert "Python" in report
        assert "Ruff" in report

    def test_format_report_groups_by_type(self, temp_project):
        """Test that report groups technologies by type."""
        pyproject = temp_project / "pyproject.toml"
        pyproject.write_text(
            """
[tool.poetry]
name = "test"

[tool.ruff]
line-length = 100
"""
        )

        detector = TechStackDetector(str(temp_project))
        stack = detector.detect_all()
        report = format_tech_stack_report(stack)

        assert "## Language" in report
        assert "## Linter" in report

    def test_format_report_includes_warnings(self, temp_project):
        """Test that report includes warnings section."""
        detector = TechStackDetector(str(temp_project))
        detector.warnings.append("Test warning")
        stack = detector.detect_all()
        report = format_tech_stack_report(stack)

        assert "## Warnings" in report
        assert "Test warning" in report
