#!/usr/bin/env python3
"""
Premium Skills Client

Client for PopKit Cloud premium skill execution API.
Handles server-side skill generation with subscription validation.

Part of Issue #152 (Server-Side Premium Skill Execution).
"""

import json
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any

from .cloud_config import DEFAULT_API_URL, resolve_cloud_config

# =============================================================================
# CONFIGURATION
# =============================================================================

POPKIT_API_URL = DEFAULT_API_URL
POPKIT_VERSION = "1.0.0"


# =============================================================================
# DATA CLASSES
# =============================================================================


@dataclass
class PremiumStatus:
    """Premium subscription status."""

    tier: str
    is_premium: bool
    user_id: str | None
    features: dict[str, bool]
    upgrade_url: str | None


@dataclass
class GeneratedFile:
    """A file generated by a premium skill."""

    path: str
    content: str


@dataclass
class MCPGeneratorResult:
    """Result from MCP server generation."""

    success: bool
    files: list[GeneratedFile]
    instructions: str
    tools: list[str]
    error: str | None = None


@dataclass
class SkillInfo:
    """Information about a premium skill."""

    id: str
    name: str
    description: str
    endpoint: str
    tier: str
    available: bool
    coming_soon: bool = False


# =============================================================================
# PREMIUM CLIENT
# =============================================================================


class PremiumClient:
    """
    Client for PopKit Cloud premium skills.

    Features:
    - MCP server generation
    - Subscription status checking
    - Premium skill listing
    """

    def __init__(self, api_key: str | None = None, api_url: str | None = None):
        """
        Initialize premium client.

        Args:
            api_key: PopKit API key (defaults to env var or saved login config)
            api_url: PopKit Cloud API URL (defaults to env var or saved login config)
        """
        resolved_key, resolved_url = resolve_cloud_config()
        self.api_key = api_key or resolved_key
        self.api_url = (api_url or resolved_url).rstrip("/")

    # =========================================================================
    # PUBLIC API
    # =========================================================================

    def get_status(self) -> PremiumStatus | None:
        """
        Get premium subscription status.

        Returns:
            PremiumStatus or None if unavailable
        """
        if not self.api_key:
            return PremiumStatus(
                tier="free",
                is_premium=False,
                user_id=None,
                features={},
                upgrade_url="https://popkit.dev/pricing",
            )

        try:
            response = self._get("/v1/premium/status")
            return PremiumStatus(
                tier=response.get("tier", "free"),
                is_premium=response.get("isPremium", False),
                user_id=response.get("userId"),
                features=response.get("features", {}),
                upgrade_url=response.get("upgrade_url"),
            )
        except Exception:
            return None

    def list_skills(self) -> list[SkillInfo]:
        """
        List available premium skills.

        Returns:
            List of SkillInfo objects
        """
        if not self.api_key:
            return []

        try:
            response = self._get("/v1/premium/skills")
            skills = response.get("skills", [])
            return [
                SkillInfo(
                    id=s.get("id", ""),
                    name=s.get("name", ""),
                    description=s.get("description", ""),
                    endpoint=s.get("endpoint", ""),
                    tier=s.get("tier", "pro"),
                    available=s.get("available", False),
                    coming_soon=s.get("coming_soon", False),
                )
                for s in skills
            ]
        except Exception:
            return []

    def generate_mcp_server(
        self,
        project_name: str,
        tech_stack: list[str],
        services: list[str] | None = None,
        dev_port: int | None = None,
        db_port: int | None = None,
        framework: str | None = None,
        database: str | None = None,
        include_embeddings: bool = True,
        include_routines: bool = True,
    ) -> MCPGeneratorResult:
        """
        Generate a custom MCP server for a project.

        Args:
            project_name: Name of the project
            tech_stack: List of technologies (e.g., ["nextjs", "prisma", "typescript"])
            services: List of services to check
            dev_port: Development server port
            db_port: Database port
            framework: Override detected framework
            database: Override detected database
            include_embeddings: Include semantic search tools
            include_routines: Include morning/nightly routines

        Returns:
            MCPGeneratorResult with files and instructions
        """
        if not self.api_key:
            return MCPGeneratorResult(
                success=False,
                files=[],
                instructions="",
                tools=[],
                error="API key required. Set POPKIT_API_KEY environment variable.",
            )

        try:
            body: dict[str, Any] = {
                "projectName": project_name,
                "techStack": tech_stack,
                "services": services or [],
                "includeEmbeddings": include_embeddings,
                "includeRoutines": include_routines,
            }

            if dev_port is not None:
                body["devPort"] = dev_port
            if db_port is not None:
                body["dbPort"] = db_port
            if framework:
                body["framework"] = framework
            if database:
                body["database"] = database

            response = self._post("/v1/premium/generate/mcp", body)

            if response.get("error"):
                return MCPGeneratorResult(
                    success=False, files=[], instructions="", tools=[], error=response.get("error")
                )

            files = [
                GeneratedFile(path=f.get("path", ""), content=f.get("content", ""))
                for f in response.get("files", [])
            ]

            return MCPGeneratorResult(
                success=response.get("success", False),
                files=files,
                instructions=response.get("instructions", ""),
                tools=response.get("tools", []),
            )

        except urllib.error.HTTPError as e:
            if e.code == 403:
                return MCPGeneratorResult(
                    success=False,
                    files=[],
                    instructions="",
                    tools=[],
                    error="Premium subscription required. Upgrade at https://popkit.dev/pricing",
                )
            body_text = e.read().decode("utf-8") if e.fp else ""
            return MCPGeneratorResult(
                success=False,
                files=[],
                instructions="",
                tools=[],
                error=f"API error {e.code}: {e.reason}\n{body_text}",
            )
        except Exception as e:
            return MCPGeneratorResult(
                success=False, files=[], instructions="", tools=[], error=str(e)
            )

    # =========================================================================
    # PROPERTIES
    # =========================================================================

    @property
    def is_available(self) -> bool:
        """Check if API key is configured."""
        return bool(self.api_key)

    # =========================================================================
    # INTERNAL METHODS
    # =========================================================================

    def _get(self, endpoint: str) -> dict[str, Any]:
        """Make GET request to API."""
        return self._request("GET", endpoint)

    def _post(self, endpoint: str, body: dict[str, Any]) -> dict[str, Any]:
        """Make POST request to API."""
        return self._request("POST", endpoint, body)

    def _request(
        self, method: str, endpoint: str, body: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """Make HTTP request to API."""
        url = f"{self.api_url}{endpoint}"

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-PopKit-Version": POPKIT_VERSION,
        }

        data = json.dumps(body).encode("utf-8") if body else None

        request = urllib.request.Request(url, data=data, headers=headers, method=method)

        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            raise e  # Re-raise for caller to handle
        except urllib.error.URLError as e:
            raise RuntimeError(f"Network error: {e.reason}")


# =============================================================================
# MODULE-LEVEL FUNCTIONS
# =============================================================================

_client: PremiumClient | None = None


def get_client() -> PremiumClient:
    """Get or create the singleton premium client."""
    global _client
    if _client is None:
        _client = PremiumClient()
    return _client


def get_status() -> PremiumStatus | None:
    """Get premium subscription status."""
    return get_client().get_status()


def is_premium() -> bool:
    """Check if user has premium access."""
    status = get_status()
    return status.is_premium if status else False


def list_skills() -> list[SkillInfo]:
    """List available premium skills."""
    return get_client().list_skills()


def generate_mcp_server(project_name: str, tech_stack: list[str], **kwargs) -> MCPGeneratorResult:
    """Generate an MCP server."""
    return get_client().generate_mcp_server(project_name, tech_stack, **kwargs)


def is_available() -> bool:
    """Check if premium client is available."""
    return get_client().is_available


# =============================================================================
# CLI INTERFACE
# =============================================================================

if __name__ == "__main__":
    import sys

    print("Premium Client Test")
    print("=" * 40)

    client = PremiumClient()

    if not client.is_available:
        print("ERROR: POPKIT_API_KEY not set")
        print("Set: export POPKIT_API_KEY=your-key-here")
        sys.exit(1)

    print("Cloud config: loaded")

    # Test status check
    print("\nTesting status check...")
    status = client.get_status()
    if status:
        print(f"Tier: {status.tier}")
        print(f"Is Premium: {status.is_premium}")
        print(f"User ID: {status.user_id}")
        print(f"Features: {status.features}")
        if status.upgrade_url:
            print(f"Upgrade URL: {status.upgrade_url}")
    else:
        print("Status check failed")

    # Test skill listing
    print("\nTesting skill listing...")
    skills = client.list_skills()
    print(f"Found {len(skills)} skills")
    for skill in skills:
        status_str = (
            "available"
            if skill.available
            else ("coming soon" if skill.coming_soon else "requires upgrade")
        )
        print(f"  - {skill.name} ({skill.tier}): {status_str}")

    # Test MCP generation (only if premium)
    if status and status.is_premium:
        print("\nTesting MCP generation...")
        result = client.generate_mcp_server(
            project_name="test-project", tech_stack=["nextjs", "typescript", "prisma"]
        )
        if result.success:
            print(f"Generated {len(result.files)} files")
            print(f"Tools: {', '.join(result.tools)}")
            print("\nFiles:")
            for f in result.files:
                print(f"  - {f.path} ({len(f.content)} bytes)")
        else:
            print(f"Generation failed: {result.error}")
    else:
        print("\nSkipping MCP generation test (requires premium)")

    print("\nAll tests completed!")
