#!/usr/bin/env python3
"""Tests for popkit_shared.providers.cursor — Cursor provider adapter."""

import json
import os
from pathlib import Path
from unittest.mock import patch

from popkit_shared.providers.base import (
    ProviderInfo,
    ToolCategory,
    ToolMapping,
)
from popkit_shared.providers.cursor import CursorAdapter
from popkit_shared.providers.registry import get_adapter, list_adapters
from popkit_shared.providers.tool_mapping import CURSOR_MAPPINGS

# =============================================================================
# Detection Tests
# =============================================================================


class TestCursorDetection:
    """Tests for Cursor detection logic."""

    def test_name_and_display_name(self):
        adapter = CursorAdapter()
        assert adapter.name == "cursor"
        assert adapter.display_name == "Cursor"

    def test_detect_returns_provider_info(self):
        adapter = CursorAdapter()
        info = adapter.detect()
        assert isinstance(info, ProviderInfo)
        assert info.name == "cursor"

    def test_detect_with_home_dir(self, tmp_path):
        """Detected as available when ~/.cursor/ exists."""
        adapter = CursorAdapter()
        cursor_dir = tmp_path / ".cursor"
        cursor_dir.mkdir()

        with patch.object(Path, "home", return_value=tmp_path):
            info = adapter.detect()
            assert info.is_available is True
            assert info.install_path == cursor_dir

    def test_detect_without_cursor(self, tmp_path):
        """Not available when no .cursor/ dir and no binary."""
        adapter = CursorAdapter()

        with (
            patch.object(Path, "home", return_value=tmp_path),
            patch("popkit_shared.providers.cursor.shutil.which", return_value=None),
            patch("popkit_shared.providers.cursor.Path.is_dir", return_value=False),
        ):
            # Patch Path(".cursor").is_dir() and Path.home()/.cursor to not exist
            info = adapter.detect()
            assert info.is_available is False
            assert info.install_path is None

    def test_detect_with_binary_on_path(self, tmp_path):
        """Detected as available when cursor binary is on PATH."""
        adapter = CursorAdapter()

        with (
            patch.object(Path, "home", return_value=tmp_path),
            patch("popkit_shared.providers.cursor.shutil.which", return_value="/usr/bin/cursor"),
        ):
            info = adapter.detect()
            assert info.is_available is True


# =============================================================================
# Config Generation Tests
# =============================================================================


class TestCursorConfigGeneration:
    """Tests for Cursor config generation."""

    def test_generate_config_creates_mcp_json(self, tmp_path):
        """Generate config creates a valid mcp-config.json."""
        adapter = CursorAdapter()
        package_dir = tmp_path / "popkit-core"
        package_dir.mkdir()
        output_dir = tmp_path / "output"

        with patch.dict(os.environ, {"POPKIT_HOME": str(tmp_path)}):
            result = adapter.generate_config(package_dir, output_dir)

        assert len(result) >= 1
        config_path = result[0]
        assert config_path.name == "mcp-config.json"
        assert config_path.is_file()

        with open(config_path, encoding="utf-8") as f:
            config = json.load(f)

        assert "mcpServers" in config
        assert "popkit" in config["mcpServers"]
        server = config["mcpServers"]["popkit"]
        assert server["command"] == "python3"
        assert server["args"] == ["-m", "popkit_mcp.server"]
        assert "POPKIT_HOME" in server["env"]

    def test_generate_config_creates_cursorrules(self, tmp_path):
        """Generate config creates .cursorrules from AGENT.md files."""
        adapter = CursorAdapter()
        package_dir = tmp_path / "popkit-core"
        agents_dir = package_dir / "agents" / "researcher"
        agents_dir.mkdir(parents=True)

        agent_md = agents_dir / "AGENT.md"
        agent_md.write_text("You are a research agent.\n\nDo research tasks.", encoding="utf-8")

        output_dir = tmp_path / "output"

        with patch.dict(os.environ, {"POPKIT_HOME": str(tmp_path)}):
            result = adapter.generate_config(package_dir, output_dir)

        # Should have mcp-config.json + at least one .cursorrules file
        assert len(result) >= 2
        rules_files = [p for p in result if ".cursorrules" in p.name]
        assert len(rules_files) == 1

        content = rules_files[0].read_text(encoding="utf-8")
        assert "Generated by PopKit" in content
        assert "You are a research agent." in content

    def test_generate_config_no_agent_md(self, tmp_path):
        """Generate config with no AGENT.md files produces only mcp-config.json."""
        adapter = CursorAdapter()
        package_dir = tmp_path / "popkit-core"
        package_dir.mkdir()
        output_dir = tmp_path / "output"

        with patch.dict(os.environ, {"POPKIT_HOME": str(tmp_path)}):
            result = adapter.generate_config(package_dir, output_dir)

        assert len(result) == 1
        assert result[0].name == "mcp-config.json"


# =============================================================================
# Tool Mapping Tests
# =============================================================================


class TestCursorToolMappings:
    """Tests for Cursor tool mappings."""

    def test_tool_mappings_match_cursor_mappings(self):
        """get_tool_mappings returns the CURSOR_MAPPINGS list."""
        adapter = CursorAdapter()
        mappings = adapter.get_tool_mappings()
        assert mappings is CURSOR_MAPPINGS

    def test_tool_mappings_have_correct_types(self):
        adapter = CursorAdapter()
        mappings = adapter.get_tool_mappings()
        assert len(mappings) > 0
        assert all(isinstance(m, ToolMapping) for m in mappings)

    def test_file_read_maps_to_read_file(self):
        adapter = CursorAdapter()
        mapping = adapter.map_tool(ToolCategory.FILE_READ)
        assert mapping is not None
        assert mapping.provider_name == "read_file"

    def test_shell_maps_to_run_terminal_cmd(self):
        adapter = CursorAdapter()
        mapping = adapter.map_tool(ToolCategory.SHELL)
        assert mapping is not None
        assert mapping.provider_name == "run_terminal_cmd"

    def test_supports_core_categories(self):
        adapter = CursorAdapter()
        assert adapter.supports_category(ToolCategory.FILE_READ)
        assert adapter.supports_category(ToolCategory.FILE_WRITE)
        assert adapter.supports_category(ToolCategory.FILE_EDIT)
        assert adapter.supports_category(ToolCategory.SHELL)
        assert adapter.supports_category(ToolCategory.CODE_SEARCH)

    def test_no_agent_spawn_support(self):
        """Cursor does not have native agent spawning."""
        adapter = CursorAdapter()
        assert not adapter.supports_category(ToolCategory.AGENT_SPAWN)


# =============================================================================
# Install / Uninstall Tests
# =============================================================================


class TestCursorInstallUninstall:
    """Tests for Cursor install/uninstall operations."""

    def test_install_creates_mcp_json(self, tmp_path):
        """Install creates ~/.cursor/mcp.json with popkit entry."""
        adapter = CursorAdapter()
        package_dir = tmp_path / "popkit-core"
        package_dir.mkdir()

        with (
            patch.object(Path, "home", return_value=tmp_path),
            patch.dict(os.environ, {"POPKIT_HOME": str(tmp_path)}),
        ):
            result = adapter.install(package_dir)

        assert result is True
        mcp_json = tmp_path / ".cursor" / "mcp.json"
        assert mcp_json.is_file()

        with open(mcp_json, encoding="utf-8") as f:
            config = json.load(f)

        assert "mcpServers" in config
        assert "popkit" in config["mcpServers"]

    def test_install_merges_with_existing(self, tmp_path):
        """Install preserves existing MCP server entries."""
        adapter = CursorAdapter()
        package_dir = tmp_path / "popkit-core"
        package_dir.mkdir()

        # Create existing mcp.json with another server
        cursor_dir = tmp_path / ".cursor"
        cursor_dir.mkdir()
        mcp_json = cursor_dir / "mcp.json"
        existing = {
            "mcpServers": {
                "other-server": {
                    "command": "node",
                    "args": ["server.js"],
                }
            }
        }
        with open(mcp_json, "w", encoding="utf-8") as f:
            json.dump(existing, f)

        with (
            patch.object(Path, "home", return_value=tmp_path),
            patch.dict(os.environ, {"POPKIT_HOME": str(tmp_path)}),
        ):
            result = adapter.install(package_dir)

        assert result is True

        with open(mcp_json, encoding="utf-8") as f:
            config = json.load(f)

        # Both entries should exist
        assert "other-server" in config["mcpServers"]
        assert "popkit" in config["mcpServers"]

    def test_install_handles_malformed_existing_json(self, tmp_path):
        """Install handles corrupted mcp.json gracefully."""
        adapter = CursorAdapter()
        package_dir = tmp_path / "popkit-core"
        package_dir.mkdir()

        cursor_dir = tmp_path / ".cursor"
        cursor_dir.mkdir()
        mcp_json = cursor_dir / "mcp.json"
        mcp_json.write_text("{invalid json", encoding="utf-8")

        with (
            patch.object(Path, "home", return_value=tmp_path),
            patch.dict(os.environ, {"POPKIT_HOME": str(tmp_path)}),
        ):
            result = adapter.install(package_dir)

        assert result is True

        with open(mcp_json, encoding="utf-8") as f:
            config = json.load(f)

        assert "popkit" in config["mcpServers"]

    def test_uninstall_removes_popkit_entry(self, tmp_path):
        """Uninstall removes popkit from mcp.json."""
        adapter = CursorAdapter()

        cursor_dir = tmp_path / ".cursor"
        cursor_dir.mkdir()
        mcp_json = cursor_dir / "mcp.json"
        config = {
            "mcpServers": {
                "popkit": {"command": "python3", "args": ["-m", "popkit_mcp.server"]},
                "other-server": {"command": "node", "args": ["server.js"]},
            }
        }
        with open(mcp_json, "w", encoding="utf-8") as f:
            json.dump(config, f)

        with patch.object(Path, "home", return_value=tmp_path):
            result = adapter.uninstall("popkit")

        assert result is True

        with open(mcp_json, encoding="utf-8") as f:
            config = json.load(f)

        assert "popkit" not in config["mcpServers"]
        assert "other-server" in config["mcpServers"]

    def test_uninstall_no_mcp_json(self, tmp_path):
        """Uninstall returns False when no mcp.json exists."""
        adapter = CursorAdapter()

        with patch.object(Path, "home", return_value=tmp_path):
            result = adapter.uninstall("popkit")

        assert result is False

    def test_uninstall_no_popkit_entry(self, tmp_path):
        """Uninstall returns False when popkit is not in mcp.json."""
        adapter = CursorAdapter()

        cursor_dir = tmp_path / ".cursor"
        cursor_dir.mkdir()
        mcp_json = cursor_dir / "mcp.json"
        with open(mcp_json, "w", encoding="utf-8") as f:
            json.dump({"mcpServers": {}}, f)

        with patch.object(Path, "home", return_value=tmp_path):
            result = adapter.uninstall("popkit")

        assert result is False


# =============================================================================
# Registry Integration Tests
# =============================================================================


class TestCursorRegistryIntegration:
    """Tests that CursorAdapter is properly registered."""

    def test_cursor_in_list_adapters(self):
        """Cursor adapter appears in the registry."""
        adapters = list_adapters()
        names = {a.name for a in adapters}
        assert "cursor" in names

    def test_get_cursor_adapter(self):
        """Can retrieve Cursor adapter by name."""
        adapter = get_adapter("cursor")
        assert adapter is not None
        assert adapter.name == "cursor"
        assert isinstance(adapter, CursorAdapter)
