/**
 * Morning Routine Command Templates
 */

export const morningCommandTemplate = `---
description: Morning health check for {{PROJECT_NAME}} (Ready to Code score 0-100)
---

# /{{PROJECT_PREFIX}}:morning - {{PROJECT_NAME}} Morning Check

Comprehensive health check for {{PROJECT_NAME}} development.

## Usage

\\\`\\\`\\\`
/{{PROJECT_PREFIX}}:morning           # Full morning report
/{{PROJECT_PREFIX}}:morning quick     # Compact summary
\\\`\\\`\\\`

## Checks

### Services

| Service | Port | Check Command |
|---------|------|---------------|
| {{FRAMEWORK}} Dev Server | {{DEV_PORT}} | \\\`curl -s localhost:{{DEV_PORT}} > /dev/null\\\` |
| {{DATABASE}} | {{DB_PORT}} | \\\`{{DB_CHECK_COMMAND}}\\\` |

### Git Status

Check for:
- Current branch
- Uncommitted changes
- Remote sync status (ahead/behind)

\\\`\\\`\\\`bash
git status --porcelain
git branch -vv | grep "^\\*"
\\\`\\\`\\\`

### Code Quality

\\\`\\\`\\\`bash
# TypeScript check (if applicable)
npx tsc --noEmit 2>&1 | head -20

# Lint check
npm run lint 2>&1 | tail -10
\\\`\\\`\\\`

### Tests

\\\`\\\`\\\`bash
npm test -- --passWithNoTests --silent 2>&1 | tail -5
\\\`\\\`\\\`

## Ready to Code Score

| Check | Points | Status |
|-------|--------|--------|
| Services running | 30 | - |
| Clean working directory | 20 | - |
| Remote sync | 10 | - |
| TypeScript clean | 15 | - |
| Tests passing | 25 | - |

**Total: 0-100**

## Quick Fix Commands

\\\`\\\`\\\`bash
# Start dev server
npm run dev

# Start database
{{DB_CHECK_COMMAND}}

# Fix TypeScript errors
npx tsc --noEmit

# Run tests
npm test
\\\`\\\`\\\`

## Output Format

Present results as:

\\\`\\\`\\\`
┌──────────────────────────────────────┐
│  MORNING ROUTINE - {{PROJECT_NAME}}  │
├──────────────────────────────────────┤
│  Git Status:     [✓/✗] [details]     │
│  Dev Server:     [✓/✗] port {{DEV_PORT}}     │
│  Database:       [✓/✗] {{DATABASE}}       │
│  TypeScript:     [✓/✗] [errors]      │
│  Tests:          [✓/✗] [passed/failed]│
├──────────────────────────────────────┤
│  Ready to Code Score: XX/100         │
└──────────────────────────────────────┘
\\\`\\\`\\\`

---
*Generated by PopKit Premium*
`;

export const morningMcpTemplate = `---
description: Morning health check via MCP (Ready to Code score 0-100)
---

# /{{PROJECT_PREFIX}}:morning - {{PROJECT_NAME}} Morning Check

Run the MCP-based morning health check.

## Usage

\\\`\\\`\\\`
/{{PROJECT_PREFIX}}:morning           # Full morning report
/{{PROJECT_PREFIX}}:morning quick     # Compact summary
\\\`\\\`\\\`

## Implementation

Run the \\\`mcp__{{MCP_SERVER_NAME}}__morning_routine\\\` MCP tool.

If unavailable, run individual checks:
- \\\`mcp__{{MCP_SERVER_NAME}}__check_database\\\`
- \\\`mcp__{{MCP_SERVER_NAME}}__check_dev_server\\\`
- \\\`mcp__{{MCP_SERVER_NAME}}__git_status\\\`
- \\\`mcp__{{MCP_SERVER_NAME}}__run_typecheck\\\`

Display the Ready to Code score and any issues.

## Output Format

Present results as:

\\\`\\\`\\\`
┌──────────────────────────────────────┐
│  MORNING ROUTINE - {{PROJECT_NAME}}  │
├──────────────────────────────────────┤
│  [MCP tool results displayed here]   │
├──────────────────────────────────────┤
│  Ready to Code Score: XX/100         │
└──────────────────────────────────────┘
\\\`\\\`\\\`

---
*Generated by PopKit Premium (MCP Wrapper Mode)*
`;
