/**
 * Nightly Routine Command Templates
 */

export const nightlyCommandTemplate = `---
description: Nightly cleanup and maintenance for {{PROJECT_NAME}} (Sleep Score 0-100)
---

# /{{PROJECT_PREFIX}}:nightly - {{PROJECT_NAME}} Nightly Cleanup

End-of-day cleanup and maintenance for {{PROJECT_NAME}}.

## Usage

\\\`\\\`\\\`
/{{PROJECT_PREFIX}}:nightly              # Full nightly report
/{{PROJECT_PREFIX}}:nightly quick        # Compact summary
/{{PROJECT_PREFIX}}:nightly --auto-fix   # Execute cleanup automatically
\\\`\\\`\\\`

## Cleanup Targets

| Category | Target | Description |
|----------|--------|-------------|
| Build Artifacts | {{BUILD_DIR}}/ | Build output directory |
| Cache | {{CACHE_DIR}}/ | Node/build cache |
| Coverage | coverage/ | Test coverage reports |
| Temp Files | *.log (7+ days) | Old log files |

### {{LANGUAGE}}-Specific Cleanup

Directories to clean: {{CLEANUP_DIRS}}
Files to clean: {{CLEANUP_FILES}}

## Cleanup Commands

\\\`\\\`\\\`bash
# Build artifacts (safe to delete)
rm -rf {{BUILD_DIR}}/

# Caches (safe to delete)
rm -rf {{CACHE_DIR}}/ .eslintcache .tsbuildinfo

# Coverage (safe to delete)
rm -rf coverage/

# Old logs
find . -name "*.log" -mtime +7 -type f -delete

# Temp files
find . -name "*.tmp" -type f -delete
find . -name ".DS_Store" -type f -delete
\\\`\\\`\\\`

## Git Maintenance

\\\`\\\`\\\`bash
# Garbage collection
git gc --auto

# Prune remote tracking branches
git fetch --prune

# Delete merged branches (except main/master)
git branch --merged main | grep -v "^\\*\\|main\\|master" | xargs -r git branch -d
\\\`\\\`\\\`

## Security Check

\\\`\\\`\\\`bash
# Audit dependencies
npm audit

# Check for outdated packages
npm outdated
\\\`\\\`\\\`

## Session State

Before ending:
1. Check for uncommitted changes
2. Capture session state to STATUS.json
3. Note any pending tasks

## Sleep Score

| Check | Points | Status |
|-------|--------|--------|
| No uncommitted changes | 30 | - |
| Session state saved | 20 | - |
| Git maintenance done | 15 | - |
| Security audit clean | 15 | - |
| Caches cleaned | 10 | - |
| Logs rotated | 10 | - |

**Total: 0-100**

## Output Format

Present results as:

\\\`\\\`\\\`
┌──────────────────────────────────────┐
│  NIGHTLY ROUTINE - {{PROJECT_NAME}}  │
├──────────────────────────────────────┤
│  Uncommitted:    [✓/✗] [count]       │
│  Session State:  [✓/✗] saved         │
│  Git Cleanup:    [✓/✗] complete      │
│  Security:       [✓/✗] [vulns]       │
│  Cache Cleaned:  [✓/✗] [size freed]  │
│  Logs Rotated:   [✓/✗] [count]       │
├──────────────────────────────────────┤
│  Sleep Score: XX/100                 │
│  Safe to close: [Yes/No]             │
└──────────────────────────────────────┘
\\\`\\\`\\\`

## Warnings

If uncommitted changes exist:
\\\`\\\`\\\`
⚠️  You have uncommitted changes!
    Consider: /{{PROJECT_PREFIX}}:commit or /popkit:git commit
\\\`\\\`\\\`

If security vulnerabilities found:
\\\`\\\`\\\`
⚠️  Security vulnerabilities detected!
    Run: npm audit fix
\\\`\\\`\\\`

---
*Generated by PopKit Premium*
`;

export const nightlyMcpTemplate = `---
description: Nightly cleanup via MCP (Sleep Score 0-100)
---

# /{{PROJECT_PREFIX}}:nightly - {{PROJECT_NAME}} Nightly Cleanup

Run the MCP-based nightly routine.

## Usage

\\\`\\\`\\\`
/{{PROJECT_PREFIX}}:nightly              # Full nightly report
/{{PROJECT_PREFIX}}:nightly quick        # Compact summary
/{{PROJECT_PREFIX}}:nightly --auto-fix   # Execute cleanup automatically
\\\`\\\`\\\`

## Implementation

Run the \\\`mcp__{{MCP_SERVER_NAME}}__nightly_routine\\\` MCP tool.

If unavailable, run individual cleanup tools:
- \\\`mcp__{{MCP_SERVER_NAME}}__git_status\\\` (check uncommitted)
- \\\`mcp__{{MCP_SERVER_NAME}}__run_lint\\\` (final quality check)

Then perform manual cleanup:
- Git maintenance: \\\`git gc --auto && git fetch --prune\\\`
- Security audit: \\\`npm audit\\\`

Display the Sleep Score and any warnings.

## Output Format

Present results as:

\\\`\\\`\\\`
┌──────────────────────────────────────┐
│  NIGHTLY ROUTINE - {{PROJECT_NAME}}  │
├──────────────────────────────────────┤
│  [MCP tool results displayed here]   │
├──────────────────────────────────────┤
│  Sleep Score: XX/100                 │
│  Safe to close: [Yes/No]             │
└──────────────────────────────────────┘
\\\`\\\`\\\`

---
*Generated by PopKit Premium (MCP Wrapper Mode)*
`;
